name = "veternitzz/rlog"
version = "0.1.0"
description = "A simple log class for the Lune runtime."
authors = ["Anthony LaPeter <anthonylapeter@gmail.com>"]
repository = "https://github.com/veternitzz/rlog"
license = "MIT"

includes = [
    "src/**/*.luau",
    "LICENSE",
    "README.md",
    "docs/**/*.md"
]

[engines]
pesde = "0.7.1"
lune = "0.10.2"

[target]
environment = "lune"
lib = "src/lib.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
